version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tally_db_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  pharmaseek-fastapi:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8030 --reload
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8030:8030"
    environment:
      - POSTGRES_DB=tally_db_1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DATABASE_URL=postgresql://postgres:root@db:5432/tally_db_1
    depends_on:
      db:
        condition: service_healthy

  rq-worker:
    build:
      context: .
    command: rq worker
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/tally_db_1

volumes:
  postgres_data:
