version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.11
    working_directory: ~/repo

jobs:
  build-and-init:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Copy .env if needed
          command: cp .env.example .env || echo ".env already exists"

      - run:
          name: Build and start all services
          command: |
            docker-compose -f docker-compose.yml -f docker-compose-db.yml up -d --build

      - run:
          name: Wait for PostgreSQL to be healthy
          command: |
            for i in {1..30}; do
              STATUS=$(docker inspect --format='{{json .State.Health.Status}}' $(docker-compose ps -q db))
              echo "DB container health: $STATUS"
              if [ "$STATUS" = "\"healthy\"" ]; then
                echo "Postgres is healthy."
                break
              fi
              sleep 2
            done
            if [ "$STATUS" != "\"healthy\"" ]; then
              echo "Postgres failed to start in time."
              docker-compose logs db
              exit 1
            fi

      - run:
          name: Show init-db logs (run_init.py)
          command: docker-compose logs init-db

      - run:
          name: Check FastAPI is up
          command: |
            curl --fail http://localhost:8030/docs || (echo "FastAPI not reachable" && exit 1)

      - run:
          name: Shut down containers
          command: docker-compose -f docker-compose.yml -f docker-compose-db.yml down

workflows:
  version: 2
  test:
    jobs:
      - build-and-init
